# Generated by Django 2.2.7 on 2020-01-21 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='depot',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
