# Generated by Django 2.2.7 on 2020-01-15 13:21

from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='truck_log_books',
            field=models.FileField(default=1, upload_to='documents/', validators=[utils.validators.validate_file_extension]),
            preserve_default=False,
        ),
    ]
