# Generated by Django 2.2.7 on 2020-01-16 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0002_rate_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rate',
            old_name='prefered_currency',
            new_name='preferred_currency',
        ),
    ]
