# Generated by Django 2.2.7 on 2020-01-16 12:10

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0003_auto_20200116_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='type',
        ),
        migrations.AddField(
            model_name='rate',
            name='price_per_kg',
            field=models.DecimalField(blank=True, decimal_places=4, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='rate',
            name='price_per_km',
            field=models.DecimalField(blank=True, decimal_places=4, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='rate',
            name='price_per_truck',
            field=models.DecimalField(blank=True, decimal_places=4, default=Decimal('0'), max_digits=12),
        ),
    ]
