# Generated by Django 2.2.7 on 2020-01-16 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0004_auto_20200116_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='companies.CargoOwnerCompany'),
        ),
    ]
