# Generated by Django 2.2.7 on 2019-11-27 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('EM', 'Employee'), ('SA', 'Shipper Admin'), ('TR', 'Transporter'), ('CO', 'Cargo Owner')], default='EM', max_length=200),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
