# Generated by Django 2.2.7 on 2020-02-05 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0007_auto_20200205_1843"),
        ("authentication", "0002_auto_20200205_1454"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="employer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employees",
                to="companies.Company",
            ),
        )
    ]
