# Generated by Django 2.2.7 on 2019-12-10 06:23

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20191209_0819'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='role',
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
