# Generated by Django 2.2.7 on 2019-12-09 05:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('employer_code', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transporter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('company_name', models.CharField(max_length=100)),
                ('company_admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transporter_company_admin', to=settings.AUTH_USER_MODEL)),
                ('company_location', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.Location')),
                ('employer_code', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transporter_company', to='companies.Employer', to_field='employer_code')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CargoOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('company_name', models.CharField(max_length=100)),
                ('company_admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cargo_company_admin', to=settings.AUTH_USER_MODEL)),
                ('company_location', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.Location')),
                ('employer_code', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cargo_company', to='companies.Employer', to_field='employer_code')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
