# Generated by Django 2.2.7 on 2020-01-15 13:21

from django.db import migrations, models
import django.db.models.deletion
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='personofcontact',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='cargoownercompany',
            name='commodities',
        ),
        migrations.RemoveField(
            model_name='cargoownercompany',
            name='contact_details',
        ),
        migrations.RemoveField(
            model_name='cargoownercompany',
            name='person_of_contact',
        ),
        migrations.RemoveField(
            model_name='transportercompany',
            name='contact_details',
        ),
        migrations.RemoveField(
            model_name='transportercompany',
            name='person_of_contact',
        ),
        migrations.RemoveField(
            model_name='transportercompany',
            name='truck_log_books',
        ),
        migrations.AddField(
            model_name='cargoownercompany',
            name='business_email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cargoownercompany',
            name='business_phone_no',
            field=models.CharField(default=1, max_length=20, validators=[utils.validators.validate_international_phone_number]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cargoownercompany',
            name='postal_code',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transportercompany',
            name='business_email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transportercompany',
            name='business_phone_no',
            field=models.CharField(default=1, max_length=20, validators=[utils.validators.validate_international_phone_number]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transportercompany',
            name='postal_code',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='personofcontact',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.TransporterCompany'),
        ),
    ]
