# Generated by Django 2.2.7 on 2020-01-22 09:42

from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personofcontact',
            name='phone',
            field=models.CharField(max_length=20, validators=[utils.validators.validate_international_phone_number]),
        ),
    ]
