# Generated by Django 2.2.7 on 2019-12-19 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargoownercompany',
            name='commodities',
            field=models.CharField(choices=[('Container', 'Container'), ('Bagged and Bulk', 'Bagged and Bulk'), ('FMCG', 'Fast-Moving Customer Goods')], max_length=30),
        ),
    ]
