# Generated by Django 2.2.7 on 2020-01-31 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("companies", "0003_auto_20200127_1141")]

    operations = [
        migrations.AlterField(
            model_name="personofcontact",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="companies.CargoOwnerCompany",
            ),
        )
    ]
