# Generated by Django 2.2.7 on 2020-02-04 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("companies", "0004_auto_20200131_1246"),
    ]

    operations = [
        migrations.AddField(
            model_name="cargoownercompany",
            name="employees",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employees+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="transportercompany",
            name="employees",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employees+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="cargoownercompany",
            name="account_number",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="cargoownercompany",
            name="business_email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="cargoownercompany",
            name="business_name",
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="cargoownercompany",
            name="business_phone_no",
            field=models.CharField(
                max_length=20,
                unique=True,
                validators=[utils.validators.validate_international_phone_number],
            ),
        ),
        migrations.AlterField(
            model_name="cargoownercompany",
            name="company_director",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="company_director+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="transportercompany",
            name="account_number",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="transportercompany",
            name="business_email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="transportercompany",
            name="business_name",
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="transportercompany",
            name="business_phone_no",
            field=models.CharField(
                max_length=20,
                unique=True,
                validators=[utils.validators.validate_international_phone_number],
            ),
        ),
        migrations.AlterField(
            model_name="transportercompany",
            name="company_director",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="company_director+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="Shypper",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("business_name", models.CharField(max_length=20, unique=True)),
                (
                    "business_type",
                    models.CharField(
                        choices=[
                            ("single", "single"),
                            ("Corporate", "Corporate"),
                            ("others", "others"),
                        ],
                        max_length=200,
                    ),
                ),
                ("account_number", models.CharField(max_length=50, unique=True)),
                ("prefered_currency", models.CharField(max_length=200)),
                ("logo", models.ImageField(upload_to="documents/")),
                (
                    "business_phone_no",
                    models.CharField(
                        max_length=20,
                        unique=True,
                        validators=[
                            utils.validators.validate_international_phone_number
                        ],
                    ),
                ),
                ("business_email", models.EmailField(max_length=254, unique=True)),
                ("postal_code", models.CharField(max_length=50, null=True)),
                (
                    "location",
                    models.CharField(help_text="Street, City, Country", max_length=200),
                ),
                (
                    "operational_regions",
                    models.CharField(
                        choices=[
                            ("locals", "locals"),
                            ("transit", "transit"),
                            ("both", "both"),
                        ],
                        max_length=30,
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                (
                    "certificate_of_incorporation",
                    models.FileField(
                        upload_to="documents/",
                        validators=[utils.validators.validate_file_extension],
                    ),
                ),
                (
                    "directors_id",
                    models.FileField(
                        upload_to="documents/",
                        validators=[utils.validators.validate_file_extension],
                    ),
                ),
                (
                    "company_director",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_director+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employees",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employees+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"abstract": False},
            managers=[("active_objects", django.db.models.manager.Manager())],
        ),
    ]
