# Generated by Django 2.2.7 on 2020-02-15 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("companies", "0007_auto_20200205_1843")]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="is_shypper",
            field=models.BooleanField(default=False),
        )
    ]
