# Generated by Django 2.2.7 on 2020-03-27 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("companies", "0008_auto_20200215_1153")]

    operations = [
        migrations.RemoveField(model_name="company", name="is_active"),
        migrations.AddField(
            model_name="company",
            name="onboarding_comments",
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="onboarding_status",
            field=models.CharField(
                choices=[
                    ("under_review", "under_review"),
                    ("approved", "approved"),
                    ("rejected", "rejected"),
                ],
                default="under_review",
                max_length=20,
            ),
        ),
    ]
