# Generated by Django 2.2.7 on 2020-03-30 10:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [("companies", "0009_auto_20200327_1743")]

    operations = [
        migrations.RemoveField(model_name="company", name="is_shypper"),
        migrations.AddField(
            model_name="company",
            name="category",
            field=models.CharField(
                choices=[
                    ("is_shypper", "is_shypper"),
                    ("transporter", "transporter"),
                    ("cargo_owner", "cargo_owner"),
                ],
                default=datetime.datetime(2020, 3, 30, 10, 7, 1, 152161, tzinfo=utc),
                max_length=255,
            ),
            preserve_default=False,
        ),
    ]
