# Generated by Django 2.2.7 on 2019-12-09 05:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0001_initial'),
        ('locations', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('truck_type', models.CharField(max_length=50)),
                ('plate_number', models.CharField(max_length=15, unique=True)),
                ('max_tonnage', models.DecimalField(decimal_places=4, max_digits=8)),
                ('drivers', models.ManyToManyField(related_name='trucks', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trucks', to='companies.Transporter')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('P', 'Pending'), ('T', 'Transit'), ('D', 'Delivered')], default='P', max_length=1)),
                ('offloading_point_contact', models.CharField(max_length=100)),
                ('offloading_point_contact_name', models.CharField(max_length=100)),
                ('loading_point_contact', models.CharField(max_length=100)),
                ('loading_point_contact_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('trip_number', models.IntegerField()),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_destinations', to='locations.Location')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='orders.Order')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_origins', to='locations.Location')),
                ('truck', models.ManyToManyField(related_name='trips', to='trips.Truck')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
