# Generated by Django 2.2.7 on 2020-03-18 12:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [("trips", "0002_event")]

    operations = [
        migrations.AddField(
            model_name="event",
            name="description",
            field=models.CharField(
                default=datetime.datetime(2020, 3, 18, 12, 24, 2, 735278, tzinfo=utc),
                max_length=100,
            ),
            preserve_default=False,
        )
    ]
