# Generated by Django 2.2.7 on 2019-12-09 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('trips', '0003_auto_20191209_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratings',
            name='reviewee',
        ),
        migrations.AddField(
            model_name='ratings',
            name='trip',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='trips.Trip'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='transporter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='companies.Transporter'),
            preserve_default=False,
        ),
    ]
