# Generated by Django 2.2.7 on 2020-03-19 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("trips", "0003_event_description")]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="trip",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="trips.Trip",
            ),
        )
    ]
