# Generated by Django 2.2.7 on 2019-12-09 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_auto_20191209_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('S', 'Started'), ('O', 'Ongoing'), ('D', 'Delivered')], default='P', max_length=1),
        ),
    ]
