# Generated by Django 2.2.7 on 2020-03-19 08:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("trips", "0004_auto_20200319_1047")]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="description",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="triggered_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
