# Generated by Django 2.2.7 on 2019-12-09 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('trips', '0005_auto_20191209_1514'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ratings',
            new_name='Rating',
        ),
    ]
