# Generated by Django 2.2.7 on 2020-01-21 13:31

import django.contrib.postgres.fields
import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('depots', '0001_initial'),
        ('rates', '0002_auto_20200121_1056'),
        ('companies', '0001_initial'),
        ('cargo_types', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1000)),
                ('cargo_tonnage', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('PD', 'Pending'), ('AS', 'Assigned'), ('AO', 'Accepted')], default='PD', max_length=2)),
                ('recurring_order', models.BooleanField(default=False)),
                ('order_type', models.CharField(choices=[('SO-SD', 'Single Origin To Single Destination'), ('SO-MD', 'Single Origin To Many Destinations'), ('MO-MD', 'Many Origins To Many Destinations'), ('MO-SD', 'Many Origins To Single Destination')], default='SO-SD', max_length=5)),
                ('desired_truck_type', models.CharField(max_length=50)),
                ('recepients', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100, null=True), size=5)),
                ('assigned', models.BooleanField(default=False)),
                ('tracking_id', models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cargo_types.Commodity')),
                ('desired_rates', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rates.Rate')),
                ('destination', models.ManyToManyField(blank=True, related_name='received_orders', to='depots.Depot')),
                ('loading_point_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loading_orders', to='companies.PersonOfContact')),
                ('offloading_point_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offloading_orders', to='companies.PersonOfContact')),
                ('origin', models.ManyToManyField(blank=True, related_name='sent_orders', to='depots.Depot')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='companies.CargoOwnerCompany')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CargoOwnerInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('number_of_trips', models.IntegerField()),
                ('description', models.CharField(max_length=1000)),
                ('charges', django.contrib.postgres.fields.hstore.HStoreField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Order', to_field='tracking_id')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
