# Generated by Django 2.2.7 on 2019-12-09 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PD', 'Pending'), ('AS', 'Assigned'), ('AO', 'Accepted')], default='PD', max_length=2),
        ),
    ]
