# Generated by Django 2.2.7 on 2020-01-29 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("orders", "0001_initial")]

    operations = [migrations.RemoveField(model_name="order", name="recepients")]
