# Generated by Django 2.2.7 on 2020-03-19 10:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("orders", "0002_remove_order_recepients")]

    operations = [
        migrations.AddField(
            model_name="order",
            name="number_of_containers",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        )
    ]
