# Generated by Django 2.2.7 on 2020-04-01 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_auto_20200331_1149"),
        ("orders", "0004_auto_20200324_0835"),
    ]

    operations = []
